### ISSUE TITLE
Cupy Issue in Google Colab

### ISSUE THREAD

**Issue by saikirananumalla** [chainer/google-colaboratory#9]
I've installed chainer cupy in colab in the given method. But when I try to do --> python -c 'import cupy'
it returns the following error

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from i3d.extract_i3d import ExtractI3D
  File "/content/drive/My Drive/BMT/i3d_features/i3d/extract_i3d.py", line 13, in <module>
    from i3d.flow_src.pwc_net import PWCNet
  File "/content/drive/My Drive/BMT/i3d_features/i3d/flow_src/pwc_net.py", line 8, in <module>
    import i3d.flow_src.correlation as correlation
  File "/content/drive/My Drive/BMT/i3d_features/i3d/flow_src/correlation.py", line 7, in <module>
    import cupy
  File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 36, in <module>
    import cupyx
  File "/usr/local/lib/python3.6/dist-packages/cupyx/__init__.py", line 6, in <module>
    from cupyx import linalg  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupyx/linalg/__init__.py", line 2, in <module>
    from cupyx.linalg import sparse  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupyx/linalg/sparse/__init__.py", line 3, in <module>
    from cupyx.linalg.sparse.solve import lschol  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupyx/linalg/sparse/solve.py", line 7, in <module>
    import cupy.sparse
  File "/usr/local/lib/python3.6/dist-packages/cupy/sparse/__init__.py", line 1, in <module>
    from cupyx.scipy.sparse.base import issparse  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupyx/scipy/__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.base import spmatrix
  File "/usr/local/lib/python3.6/dist-packages/cupyx/scipy/sparse/__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.coo import coo_matrix  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupyx/scipy/sparse/coo.py", line 11, in <module>
    from cupyx.scipy.sparse import csr
  File "/usr/local/lib/python3.6/dist-packages/cupyx/scipy/sparse/csr.py", line 10, in <module>
    from cupyx.scipy.sparse import compressed
  File "/usr/local/lib/python3.6/dist-packages/cupyx/scipy/sparse/compressed.py", line 10, in <module>
    from cupy.creation import basic
  File "/usr/local/lib/python3.6/dist-packages/cupy/creation/__init__.py", line 6, in <module>
    from cupy.creation import from_data  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupy/creation/from_data.py", line 2, in <module>
    from cupy.core import fusion
  File "cupy/core/fusion.pyx", line 11, in init cupy.core.fusion
ImportError: cannot import name _is_fusing

**Comment by kmaehashi** [comment]
Closing as CuPy is now part of the official Colab enviornment.
